"""Deck previews carry layout, not just text.

The previous reader collected a title and a flat list of lines per slide. A
slide whose content was one full-bleed photograph therefore came back with an
empty title and no lines, and the viewer drew an empty rectangle — while decks
generated by this app routinely contain images, so the thing most worth seeing
was the thing it could not show.
"""
from __future__ import annotations

import pytest

from primnox2.assets import preview

pptx = pytest.importorskip("pptx", reason="python-pptx not installed")
PIL = pytest.importorskip("PIL", reason="Pillow not installed")


@pytest.fixture
def deck(tmp_path):
    """A deck shaped like the ones this app generates: a titled slide mixing an
    image with styled text, and a slide that is nothing but a picture."""
    from PIL import Image
    from pptx import Presentation
    from pptx.util import Inches, Pt

    swatch = tmp_path / "swatch.png"
    Image.new("RGB", (400, 300), (30, 90, 160)).save(swatch)

    p = Presentation()
    one = p.slides.add_slide(p.slide_layouts[5])
    one.shapes.title.text = "CMF Headphone Pro"
    one.shapes.add_picture(str(swatch), Inches(1), Inches(2), Inches(4), Inches(3))
    box = one.shapes.add_textbox(Inches(5.5), Inches(2), Inches(3.5), Inches(1))
    box.text_frame.text = "Active noise cancellation"
    run = box.text_frame.paragraphs[0].runs[0]
    run.font.size = Pt(20)
    run.font.bold = True
    one.notes_slide.notes_text_frame.text = "Mention the 40h battery."

    two = p.slides.add_slide(p.slide_layouts[6])          # blank layout
    two.shapes.add_picture(str(swatch), Inches(0), Inches(0),
                           p.slide_width, p.slide_height)

    out = tmp_path / "deck.pptx"
    p.save(out)
    return out


def test_a_picture_only_slide_is_not_empty(deck):
    """The exact regression. Under the old reader this slide had no title, no
    lines, and nothing to draw."""
    slide = preview._slides(deck)["slides"][1]
    images = [s for s in slide["shapes"] if s["type"] == "image"]
    assert len(images) == 1, "the picture was dropped"
    box = images[0]["box"]
    assert box["w"] == pytest.approx(1.0, abs=0.01)
    assert box["h"] == pytest.approx(1.0, abs=0.01), "a full-bleed image lost its size"


def test_shapes_carry_their_position_as_fractions(deck):
    """Fractions, not EMU: the viewer draws into whatever width it has, and a
    layout expressed in absolute units cannot survive that."""
    slide = preview._slides(deck)["slides"][0]
    placed = [s for s in slide["shapes"] if s["box"]]
    assert placed, "no shape was placed"
    for s in placed:
        for k in ("x", "y", "w", "h"):
            assert 0.0 <= s["box"][k] <= 1.0, f"{k} is not a fraction: {s['box']}"


def test_text_keeps_its_size_and_weight(deck):
    slide = preview._slides(deck)["slides"][0]
    styled = [s for s in slide["shapes"]
              if s["type"] == "text" and s["text"].startswith("Active")]
    assert styled, "the styled text box is missing"
    assert styled[0]["size"] == pytest.approx(20.0)
    assert styled[0]["bold"] is True


def test_aspect_comes_from_the_deck(deck):
    """A 4:3 template must not be drawn in a 16:9 frame."""
    assert preview._slides(deck)["aspect"] == pytest.approx(4 / 3, abs=0.01)


def test_speaker_notes_are_captured(deck):
    assert preview._slides(deck)["slides"][0]["notes"] == "Mention the 40h battery."


def test_reading_order_survives_for_screen_readers(deck):
    """`lines` is still produced. It is what a screen reader follows and what
    search would index; the positional shapes are for drawing, not for reading."""
    slide = preview._slides(deck)["slides"][0]
    assert any("Active noise cancellation" in l for l in slide["lines"])


def test_image_bytes_are_fetchable_by_the_index_handed_out(deck):
    data = preview._slides(deck)
    for ref in range(data["images"]):
        found = preview.slide_image(deck, ref)
        assert found is not None, f"image {ref} was advertised but cannot be fetched"
        blob, content_type = found
        assert blob, "empty image blob"
        assert content_type.startswith("image/")


def test_an_out_of_range_image_is_refused_not_guessed(deck):
    assert preview.slide_image(deck, 99) is None
    assert preview.slide_image(deck, -1) is None


def test_describe_never_ships_raw_image_bytes(deck):
    """`_image_blobs` is not JSON-serialisable and a deck of photographs would
    be tens of megabytes on a call that only describes the deck."""
    described = preview.describe({
        "id": "asset_x", "original_name": "deck.pptx",
        "path": str(deck), "bytes": 0, "mime": None,
    })
    assert described["kind"] == "slides"
    assert "_image_blobs" not in described
    import json
    json.dumps(described)          # raises if any bytes leaked through
