/**
 * Download the app's webfonts from Google Fonts into `public/fonts/` and
 * generate `src/styles/fonts.css` with local @font-face rules.
 *
 * Why this exists: `tailwind.css` used to `@import` the Google Fonts stylesheet
 * directly. For a desktop app that advertises running entirely on your machine
 * that is wrong twice over — every launch announced itself to a Google server
 * (IP, User-Agent, timing), and with no network the app fell back to system
 * fonts and rendered visibly wrong. Vendoring fixes both.
 *
 * Syne, DM Sans and JetBrains Mono are all SIL Open Font License 1.1, which
 * permits redistribution; see public/fonts/OFL.txt.
 *
 * Re-run with:  node scripts/vendor-fonts.mjs
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const FONT_DIR = resolve(HERE, '../public/fonts');
const CSS_OUT = resolve(HERE, '../src/styles/fonts.css');

// A modern browser UA is required, or Google serves legacy TTF instead of woff2.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// Matches the weights the app actually renders. JetBrains Mono 700 is included
// because ~87 call sites render mono at font-bold; without it the browser
// synthesises a fake bold.
const QUERY =
  'family=Syne:wght@400;500;600;700;800' +
  '&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;1,9..40,300' +
  '&family=JetBrains+Mono:wght@400;500;700' +
  '&display=swap';

// Only Latin subsets ship. The Greek/Cyrillic/Vietnamese subsets Google serves
// would roughly triple the payload for glyphs this UI never renders.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function main() {
  await mkdir(FONT_DIR, { recursive: true });

  const res = await fetch(`https://fonts.googleapis.com/css2?${QUERY}`, {
    headers: { 'User-Agent': UA },
  });
  if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
  const css = await res.text();

  // Google emits `/* subset */` comments before each @font-face block.
  const blocks = css.split(/\/\*\s*([a-z-]+)\s*\*\//i).slice(1);
  const faces = [];

  for (let i = 0; i < blocks.length; i += 2) {
    const subset = blocks[i].trim();
    const body = blocks[i + 1] ?? '';
    if (!KEEP_SUBSETS.has(subset)) continue;

    const family = body.match(/font-family:\s*'([^']+)'/)?.[1];
    const style = body.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal';
    const weight = body.match(/font-weight:\s*([\d\s]+)/)?.[1]?.trim() ?? '400';
    const stretch = body.match(/font-stretch:\s*([^;]+)/)?.[1]?.trim();
    const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    const range = body.match(/unicode-range:\s*([^;]+)/)?.[1]?.trim();
    if (!family || !url) continue;

    const name = `${slug(family)}-${slug(weight)}-${style}-${subset}.woff2`;
    const bin = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`font download failed: ${url}`);
    await writeFile(resolve(FONT_DIR, name), Buffer.from(await bin.arrayBuffer()));

    faces.push({ family, style, weight, stretch, name, range });
    console.log(`  ${name}`);
  }

  if (!faces.length) throw new Error('no @font-face blocks parsed — CSS format changed?');

  const out = [
    '/* GENERATED by scripts/vendor-fonts.mjs — do not edit by hand.',
    ' *',
    ' * Self-hosted so the app never contacts Google at runtime and renders',
    ' * correctly with no network. Files live in public/fonts/ and are served',
    ' * from the app bundle. Re-run the script to refresh.',
    ' *',
    ' * Syne, DM Sans, JetBrains Mono — SIL Open Font License 1.1.',
    ' */',
    '',
    ...faces.map((f) =>
      [
        '@font-face {',
        `  font-family: '${f.family}';`,
        `  font-style: ${f.style};`,
        `  font-weight: ${f.weight};`,
        f.stretch ? `  font-stretch: ${f.stretch};` : null,
        '  font-display: swap;',
        `  src: url('/fonts/${f.name}') format('woff2');`,
        f.range ? `  unicode-range: ${f.range};` : null,
        '}',
      ]
        .filter(Boolean)
        .join('\n'),
    ),
    '',
  ].join('\n');

  await writeFile(CSS_OUT, out);
  console.log(`\n${faces.length} faces -> ${CSS_OUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
