import { useCallback, useEffect, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, StickyNote } from 'lucide-react';
import { API } from '../lib/crs';

type Box = { x: number; y: number; w: number; h: number } | null;
type Shape =
  | { type: 'text'; text: string; box: Box; title?: boolean;
      size?: number | null; bold?: boolean; align?: string | null }
  | { type: 'image'; ref: number; box: Box; alt?: string };
type Slide = { index: number; title: string; lines: string[];
               shapes: Shape[]; notes: string };

/* A deck, shown as a deck.
 *
 * The previous viewer listed each slide's text in a 16:9 box, which looked like
 * a slide and shared nothing else with one: no images, no positions, no sizes.
 * A slide that was one photograph rendered as an empty rectangle, and decks
 * generated by this app routinely contain images — so the thing most worth
 * seeing was the thing it could not show.
 *
 * Every shape is placed from its own fractional box, so the layout is the
 * deck's rather than an approximation of it, and it survives being drawn at any
 * width. Font sizes scale with the surface for the same reason: a 44pt title
 * laid out for a 13.3in slide has to shrink with the container or it overflows
 * a preview pane.
 */
export function SlideDeck({ assetId, slides, aspect }: {
  assetId: string; slides: Slide[]; aspect: number;
}) {
  const [at, setAt] = useState(0);
  const [notesOpen, setNotesOpen] = useState(false);
  const surface = useRef<HTMLDivElement>(null);
  const [width, setWidth] = useState(0);

  const go = useCallback((n: number) => {
    setAt(Math.min(slides.length - 1, Math.max(0, n)));
  }, [slides.length]);

  /* Point sizes are absolute; the surface is not. Measuring it lets a 44pt
     title render at 44pt-relative-to-this-box instead of 44 CSS pixels, which
     is the difference between a title bar and a title that wraps four times. */
  useEffect(() => {
    const el = surface.current;
    if (!el) return;
    const ro = new ResizeObserver(([e]) => setWidth(e.contentRect.width));
    ro.observe(el);
    setWidth(el.getBoundingClientRect().width);
    return () => ro.disconnect();
  }, []);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      /* Never steal a key from a field. This listener is on `window`, so
         without the guard an arrow key typed into ANY input while the viewer is
         open moved the deck instead of the caret — and `preventDefault` meant
         the caret did not move at all. A viewer that breaks text editing
         anywhere on the page is a worse bug than one without shortcuts.

         Modifier chords are left alone too: Alt+Left is the browser's Back. */
      const t = e.target as HTMLElement | null;
      if (t && (t.isContentEditable ||
                /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName))) return;
      if (e.altKey || e.metaKey || e.ctrlKey) return;

      if (e.key === 'ArrowRight' || e.key === 'PageDown') { e.preventDefault(); go(at + 1); }
      if (e.key === 'ArrowLeft' || e.key === 'PageUp') { e.preventDefault(); go(at - 1); }
      if (e.key === 'Home') { e.preventDefault(); go(0); }
      if (e.key === 'End') { e.preventDefault(); go(slides.length - 1); }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [at, go, slides.length]);

  if (slides.length === 0) {
    return <p className="px-label p-8">This deck has no slides.</p>;
  }

  const slide = slides[at];
  // A 10in-wide slide is 720pt across. Scaling by the rendered width over that
  // keeps every point size proportional to the surface it is drawn on.
  const scale = width ? width / 720 : 1;

  return (
    <div className="flex flex-col h-full min-h-0">
      <div className="flex-1 min-h-0 overflow-auto custom-scrollbar p-6">
        <div ref={surface}
          className="relative mx-auto w-full max-w-[54rem] rounded-xl overflow-hidden
                     border border-on-surface/[0.10] bg-inverse-surface"
          style={{ aspectRatio: String(aspect || 16 / 9) }}
          role="group" aria-label={`Slide ${slide.index} of ${slides.length}`}>

          {slide.shapes.map((s, i) => {
            if (!s.box) return null;                  // unplaceable — see below
            const style: React.CSSProperties = {
              position: 'absolute',
              left: `${s.box.x * 100}%`, top: `${s.box.y * 100}%`,
              width: `${s.box.w * 100}%`, height: `${s.box.h * 100}%`,
            };
            if (s.type === 'image') {
              return (
                /* Deliberately NOT loading="lazy". Only the current slide is
                   rendered, so every image here is already on screen and is the
                   content — deferring it left the slide blank until something
                   nudged the observer, which reads as the picture failing to
                   load rather than as an optimisation. `decoding="async"` keeps
                   a large photograph off the main thread without delaying the
                   request itself. */
                <img key={i} src={`${API}/assets/${assetId}/slide-image/${s.ref}`}
                  alt={s.alt || ''} style={style} decoding="async"
                  className="object-contain" />
              );
            }
            return (
              <div key={i} style={{
                ...style,
                fontSize: s.size ? `${s.size * scale}px` : undefined,
                fontWeight: s.bold || s.title ? 700 : 400,
                textAlign: (s.align as any) || undefined,
              }}
                className="overflow-hidden whitespace-pre-wrap leading-snug
                           text-inverse-on-surface">
                {s.text}
              </div>
            );
          })}

          {/* Anything python-pptx could not place — a placeholder inheriting its
              geometry from a layout — would otherwise vanish silently. Better
              listed below the slide than dropped without a word. */}
          {slide.shapes.some(s => !s.box) && (
            <div className="absolute inset-x-0 bottom-0 bg-inverse-surface/85 p-2">
              <p className="px-label mb-1">Unplaced content</p>
              {slide.shapes.filter(s => !s.box && s.type === 'text').map((s, i) => (
                <p key={i} className="text-[11px] text-inverse-on-surface/70">
                  {(s as any).text}
                </p>
              ))}
            </div>
          )}
        </div>

        {notesOpen && (
          <div className="mx-auto mt-3 w-full max-w-[54rem] rounded-xl border
                          border-on-surface/[0.10] p-4">
            <p className="px-label mb-1.5">Speaker notes</p>
            <p className="whitespace-pre-wrap text-sm leading-6 text-on-surface/75">
              {slide.notes || <span className="opacity-40">None on this slide.</span>}
            </p>
          </div>
        )}
      </div>

      {/* Filmstrip and controls. A deck is navigated, not scrolled — stacking
          thirty slides vertically made "go to slide 12" a scroll-and-count. */}
      <div className="shrink-0 border-t border-on-surface/[0.07] px-4 py-2
                      flex items-center gap-2">
        <button onClick={() => go(at - 1)} disabled={at === 0}
          aria-label="Previous slide"
          className="px-interactive p-1.5 rounded-lg text-on-surface/55
                     hover:text-on-surface hover:bg-on-surface/[0.05]
                     disabled:opacity-25 disabled:pointer-events-none">
          <ChevronLeft size={16} aria-hidden="true" />
        </button>

        <ol className="flex-1 flex items-center gap-1 overflow-x-auto custom-scrollbar">
          {slides.map((s, i) => (
            <li key={s.index}>
              <button onClick={() => go(i)}
                aria-label={`Slide ${s.index}${s.title ? `: ${s.title}` : ''}`}
                aria-current={i === at ? 'true' : undefined}
                className={`px-interactive shrink-0 rounded px-2 py-1 font-mono
                            text-[10px] tabular-nums
                  ${i === at ? 'bg-on-surface/[0.10] text-on-surface'
                             : 'text-on-surface/40 hover:text-on-surface/80'}`}>
                {s.index}
              </button>
            </li>
          ))}
        </ol>

        <span className="px-label shrink-0 tabular-nums">
          {slide.index} / {slides.length}
        </span>

        <button onClick={() => setNotesOpen(o => !o)}
          aria-label="Speaker notes" aria-pressed={notesOpen}
          title={slide.notes ? 'Speaker notes' : 'No notes on this slide'}
          className={`px-interactive p-1.5 rounded-lg
            ${notesOpen ? 'text-on-surface bg-on-surface/[0.07]'
                        : 'text-on-surface/45 hover:text-on-surface'}
            ${slide.notes ? '' : 'opacity-40'}`}>
          <StickyNote size={15} aria-hidden="true" />
        </button>

        <button onClick={() => go(at + 1)} disabled={at === slides.length - 1}
          aria-label="Next slide"
          className="px-interactive p-1.5 rounded-lg text-on-surface/55
                     hover:text-on-surface hover:bg-on-surface/[0.05]
                     disabled:opacity-25 disabled:pointer-events-none">
          <ChevronRight size={16} aria-hidden="true" />
        </button>
      </div>
    </div>
  );
}
