# backend/skills/pdf_skill.py
import time
from pathlib import Path
from skills.base_skill import BaseSkill, SkillContext, SkillResult
from logger import get_logger

log = get_logger("skill.pdf")


class PDFSkill(BaseSkill):
    name = "PDF Specialist"
    description = "Read, summarize, and generate PDF documents."
    supported_extensions = ["pdf"]
    trigger_words = [
        "summarize this pdf", "read this pdf", "what's in this pdf",
        "create pdf", "generate pdf", "make a pdf", "create a pdf", "make pdf"
    ]
    REQUIRES_PIP = ["pypdf", "reportlab"]

    @property
    def input_schema(self) -> dict:
        schema = super().input_schema
        schema["properties"]["intent"] = {
            "type": "string",
            "enum": ["read", "generate"],
            "description": "Whether to read an existing PDF or generate a new one"
        }
        return schema

    def execute(self, ctx: SkillContext) -> SkillResult:
        from pypdf import PdfReader
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet
        from brain import think

        intent = ctx.user_message.lower() if ctx.user_message else ""
        if any(w in intent for w in ["create pdf", "generate pdf", "make a pdf", "create a pdf", "make pdf"]):
            return self._generate_pdf(ctx, think, SimpleDocTemplate, Paragraph, Spacer, getSampleStyleSheet, letter)

        if not ctx.file_path:
            return SkillResult(success=False, error="no pdf file provided for reading.")

        return self._read_pdf(ctx, PdfReader, think)

    def _read_pdf(self, ctx: SkillContext, PdfReader, think) -> SkillResult:
        log.info(f"PDF Specialist (Read): {ctx.file_path}")
        try:
            reader = PdfReader(ctx.file_path)
            text = ""
            for i, page in enumerate(reader.pages):
                log.debug(f"Extracting page {i+1}...")
                text += page.extract_text() + "\n"

            prompt = ctx.user_message or "Summarize this PDF."
            resp = think(f"PDF TEXT:\n{text[:10000]}\n\nTASK: {prompt}")
            content = resp.get("choices", [{}])[0].get("message", {}).get("content", "failed to read pdf.")
            return SkillResult(success=True, output_text=content)
        except Exception as e:
            log.error(f"PDF read failed: {e}", exc_info=True)
            return SkillResult(success=False, error=str(e))

    def _generate_pdf(self, ctx: SkillContext, think, SimpleDocTemplate, Paragraph, Spacer, getSampleStyleSheet, letter) -> SkillResult:
        log.info("PDF Specialist (Generate)")
        try:
            output_dir = Path.home() / "Documents" / "Primnox" / "Generated"
            output_dir.mkdir(parents=True, exist_ok=True)
            pdf_path = output_dir / f"doc_{time.strftime('%Y%m%d_%H%M%S')}.pdf"

            gen_prompt = (
                f"TASK: Write the raw content for a PDF based on: '{ctx.user_message}'. "
                "CRITICAL CONSTRAINTS: "
                "1. Output ONLY the document content. "
                "2. NO conversational filler. "
                "3. NO meta-talk about the process. "
                "4. Use '#' for section headers. "
                "5. Maintain your persona: lowercase only, no periods."
            )
            resp = think(gen_prompt)
            if "error" in resp:
                return SkillResult(success=False, error=f"brain failed: {resp['error']}")

            content = resp.get("choices", [{}])[0].get("message", {}).get("content", "").strip()
            if not content:
                return SkillResult(success=False, error="no content generated by brain.")

            doc = SimpleDocTemplate(str(pdf_path), pagesize=letter)
            styles = getSampleStyleSheet()
            story = []
            for line in content.split("\n"):
                if line.strip():
                    if line.startswith("#"):
                        story.append(Paragraph(line.replace("#", "").strip(), styles["Heading1"]))
                    else:
                        story.append(Paragraph(line.strip(), styles["BodyText"]))
                    story.append(Spacer(1, 12))
            doc.build(story)

            log.info(f"PDF generated: {pdf_path}")
            return SkillResult(
                success=True,
                output_text=f"pdf generated successfully. saved to {pdf_path}",
                output_path=str(pdf_path)
            )
        except Exception as e:
            log.error(f"PDF generate failed: {e}", exc_info=True)
            return SkillResult(success=False, error=str(e))


if __name__ == "__main__":
    import sys
    skill = PDFSkill()
    arg = sys.argv[1] if len(sys.argv) > 1 else None
    ctx = SkillContext(
        file_path=arg if arg and arg.endswith(".pdf") else None,
        user_message=None if (arg and arg.endswith(".pdf")) else arg
    )
    print(skill.run(ctx))
