# backend/skills/ppt_skill.py
from pptx import Presentation
from pptx.util import Inches, Pt
import time
import json
import re
from pathlib import Path
from brain import think
from skills.base_skill import BaseSkill
from logger import get_logger

log = get_logger("skill.ppt")

class PPTSkill(BaseSkill):
    name = "PPT Specialist"
    supported_extensions = ["pptx"]
    trigger_words = [
        "create ppt", "make a presentation", "generate powerpoint", 
        "create powerpoint", "create a ppt", "make a ppt"
    ]

    def execute(self, file_path=None, user_message=None):
        log.info("Executing PPT Specialist (Generate)")
        try:
            output_dir = Path.home() / "Documents" / "Primnox" / "Generated"
            output_dir.mkdir(parents=True, exist_ok=True)
            
            timestamp = time.strftime("%Y%m%d_%H%M%S")
            ppt_path = output_dir / f"presentation_{timestamp}.pptx"
            
            # Use Brain to structure the content into JSON
            log.debug("Asking brain to generate content for PPT (JSON format)...")
            json_prompt = (
                f"TASK: Generate a presentation outline for: '{user_message}'. "
                "CRITICAL CONSTRAINTS: "
                "1. Output a JSON ARRAY of objects representing slides. "
                "2. Each object must have: 'title' (string) and 'content' (a list of bullet point strings). "
                "3. Use your persona: lowercase only, no periods for all text values. "
                "4. Output ONLY the raw JSON array. NO conversational filler, NO meta-talk, NO markdown blocks."
            )
            
            resp = think(json_prompt)
            if "error" in resp:
                log.error(f"Brain failed to generate content: {resp['error']}")
                return {"success": False, "error": f"brain failed: {resp['error']}"}

            content = resp.get("choices", [{}])[0].get("message", {}).get("content", "").strip()
            
            if not content or content == "ERROR":
                 return {"success": False, "error": "no content generated by brain."}
            
            # Clean JSON (remove markdown code blocks if any)
            clean_json = re.sub(r'```json\n|```', '', content).strip()
            
            try:
                slides_data = json.loads(clean_json)
            except json.JSONDecodeError as e:
                log.error(f"Failed to parse JSON from brain: {e}")
                # Fallback: simple text analysis if JSON fails
                return {"success": False, "error": "failed to structure presentation content."}

            # Create Presentation
            prs = Presentation()
            
            # Use Layout 1 (Title and Content) for most slides
            # Use Layout 0 (Title Slide) for the first one
            
            for i, slide_info in enumerate(slides_data):
                layout = prs.slide_layouts[0] if i == 0 else prs.slide_layouts[1]
                slide = prs.slides.add_slide(layout)
                
                title_shape = slide.shapes.title
                body_shape = slide.placeholders[1] if len(slide.placeholders) > 1 else None
                
                title_shape.text = slide_info.get("title", "Untitled Slide")
                
                if body_shape:
                    tf = body_shape.text_frame
                    tf.text = "" # Clear default
                    for point in slide_info.get("content", []):
                        p = tf.add_paragraph()
                        p.text = point
                        p.level = 0
            
            prs.save(str(ppt_path))
            log.info(f"PPT generated successfully: {ppt_path}")
            
            return {
                "success": True, 
                "output_text": f"ppt generated successfully. saved to {ppt_path}",
                "output_path": str(ppt_path),
                "skill_name": self.name
            }
        except Exception as e:
            log.error(f"PPT Specialist (Generate) failed: {e}", exc_info=True)
            return {"success": False, "error": str(e)}

if __name__ == "__main__":
    import sys
    skill = PPTSkill()
    if len(sys.argv) > 1:
        print(skill.execute(user_message=sys.argv[1]))
    else:
        print(skill.execute(user_message="create a ppt about the future of ai"))
