# backend/skills/ppt_skill.py
import time
import json
import re
from pathlib import Path
from skills.base_skill import BaseSkill, SkillContext, SkillResult
from logger import get_logger

log = get_logger("skill.ppt")


class PPTSkill(BaseSkill):
    name = "PPT Specialist"
    description = "Generate PowerPoint presentations from a natural-language prompt."
    supported_extensions = ["pptx"]
    trigger_words = [
        "create ppt", "make a presentation", "generate powerpoint",
        "create powerpoint", "create a ppt", "make a ppt"
    ]
    REQUIRES_PIP = ["pptx"]

    def execute(self, ctx: SkillContext) -> SkillResult:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from brain import think

        log.info("PPT Specialist (Generate)")
        try:
            output_dir = Path.home() / "Documents" / "Primnox" / "Generated"
            output_dir.mkdir(parents=True, exist_ok=True)
            ppt_path = output_dir / f"presentation_{time.strftime('%Y%m%d_%H%M%S')}.pptx"

            json_prompt = (
                f"TASK: Generate a presentation outline for: '{ctx.user_message}'. "
                "CRITICAL CONSTRAINTS: "
                "1. Output a JSON ARRAY of objects representing slides. "
                "2. Each object must have: 'title' (string) and 'content' (a list of bullet point strings). "
                "3. Use your persona: lowercase only, no periods for all text values. "
                "4. Output ONLY the raw JSON array. NO conversational filler, NO meta-talk, NO markdown blocks."
            )

            resp = think(json_prompt)
            if "error" in resp:
                return SkillResult(success=False, error=f"brain failed: {resp['error']}")

            content = resp.get("choices", [{}])[0].get("message", {}).get("content", "").strip()
            if not content:
                return SkillResult(success=False, error="no content generated by brain.")

            clean_json = re.sub(r"```json\n|```", "", content).strip()
            try:
                slides_data = json.loads(clean_json)
            except json.JSONDecodeError as e:
                log.error(f"JSON parse failed: {e}")
                return SkillResult(success=False, error="failed to structure presentation content.")

            prs = Presentation()
            for i, slide_info in enumerate(slides_data):
                layout = prs.slide_layouts[0] if i == 0 else prs.slide_layouts[1]
                slide = prs.slides.add_slide(layout)
                slide.shapes.title.text = slide_info.get("title", "Untitled Slide")
                body = slide.placeholders[1] if len(slide.placeholders) > 1 else None
                if body:
                    tf = body.text_frame
                    tf.text = ""
                    for point in slide_info.get("content", []):
                        p = tf.add_paragraph()
                        p.text = point
                        p.level = 0

            prs.save(str(ppt_path))
            log.info(f"PPT generated: {ppt_path}")
            return SkillResult(
                success=True,
                output_text=f"ppt generated successfully. saved to {ppt_path}",
                output_path=str(ppt_path)
            )
        except Exception as e:
            log.error(f"PPT generate failed: {e}", exc_info=True)
            return SkillResult(success=False, error=str(e))


if __name__ == "__main__":
    import sys
    skill = PPTSkill()
    prompt = sys.argv[1] if len(sys.argv) > 1 else "create a ppt about the future of ai"
    print(skill.run(SkillContext(user_message=prompt)))
