"""Primnox2 local vault — 12-word seed-phrase encryption for primnox.db at rest.

Ported from V1's backend/local_vault.py (and the mnemonic math from V1's
backup_manager.py, inlined here rather than cross-imported so v2 has no
dependency on the V1 tree). Same scheme, one database instead of two: CRS §4.1
keeps everything — conversations, memory, the knowledge graph — in a single
primnox.db, so there is exactly one file to encrypt.

Mnemonic (12 BIP-39 words, standard English wordlist bundled at
website/wordlist.txt, shared with V1)
  → PBKDF2-SHA512(mnemonic, b"primnox2-local", 600_000 iter) → 32-byte AES-256 key
  → key cached in OS keychain (keyring) so the app can unlock itself on
    normal startup without re-prompting every time
  → AES-256-GCM(gzip(primnox.db bytes)) → primnox.db.vault

The salt is distinct from both V1's local-vault salt (b"primnox-local") and
V1's backup salt (b"primnox-backup"), and from V1's own two mutually-distinct
salts for the same reason V1 gives: a phrase reused across products or across
local-vault-vs-backup must never derive the same key in more than one place.

.vault binary format (identical to V1's):
  Offset  Size   Field
  ──────────────────────────────────────────
  0       4      Magic  b"PRN2"
  4       1      Version 0x01
  5       12     GCM nonce (random per encryption)
  17      N      AES-256-GCM ciphertext (gzip-compressed payload)
                 ↑ last 16 bytes of ciphertext are the GCM auth tag

SAFETY MODEL — what is safe to call when, and why:

  setup_vault() and sync_vault() never touch the live plaintext file. They
  read it, encrypt a COPY to primnox.db.vault, and leave the original in
  place — matching V1's own "leaves the plaintext db in place (so the running
  app keeps working without a restart)". That makes them safe to call from a
  request handler at any time: nothing about the live database changes.

  lock_vault() is the one destructive operation — it secure-deletes the
  plaintext after verifying the .vault it just wrote decrypts back to the
  same bytes. It must only run when nothing else can be mid-write, which in
  this codebase means: after the scheduler's worker threads have been told to
  stop AND joined (app.py's shutdown hook does both before calling this).
  storage/db.py's own connection cache is per-thread with no cross-thread
  invalidation (see its configure() docstring) — the same constraint that
  makes db.configure() itself "must be called before the scheduler starts,
  which is the one place production calls it". lock_vault() inherits that
  constraint rather than solving it.

  unlock_vault() only ever runs automatically in app.py's startup handler,
  before db.configure()/db.init()/scheduler.start() — the one point in the
  process where no other thread can hold a stale connection, because no
  other thread exists yet.
"""

from __future__ import annotations

import gzip
import hashlib
import logging
import os
import secrets
import sys
from pathlib import Path
from typing import Optional

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

log = logging.getLogger("primnox2.vault")

MAGIC = b"PRN2"
VERSION = 0x01

_KEYRING_SERVICE = "primnox2-vault"
_KEYRING_USER = "vault-key"
_KEYRING_USER_PHRASE = "vault-phrase"

_SALT = b"primnox2-local"

# Shared with V1: one 2048-word BIP-39 English wordlist for the whole product,
# so a phrase generated by either backend is legible to a user who only ever
# sees one of them, and there is a single file to keep correct.
#
# In a frozen build there is no repo root: __file__ resolves somewhere under
# PyInstaller's extraction temp dir, so the bundled locations are checked
# first. Same shape of problem privacy/mirror.py's _resolve_model_source()
# already exists to avoid for the PII model.
#
# The dev-tree lookup WALKS UP rather than counting parents. It used to be
# `parents[4]`, which was correct while the backend sat at v2/backend and
# silently wrong the moment it moved to the repo root — one level shallower,
# so it resolved to C:\website\wordlist.txt and every vault test failed with
# a path nobody recognised. A hard-coded ancestor count encodes the directory
# depth of the file that reads it, which is a fact no one thinks to update
# when moving a tree. Searching upward encodes the thing that is actually
# true: the wordlist lives in `website/` somewhere above this file.
def _wordlist_path() -> Path:
    candidates = []
    base = getattr(sys, "_MEIPASS", None)
    if base:
        candidates.append(Path(base) / "wordlist.txt")
        candidates.append(Path(sys.executable).resolve().parent / "wordlist.txt")
    here = Path(__file__).resolve()
    candidates.extend(parent / "website" / "wordlist.txt" for parent in here.parents)
    for path in candidates:
        if path.is_file():
            return path
    # Unlike the PII model there is no fallback (no "download it instead") —
    # a missing wordlist means BIP-39 generation and validation cannot work
    # at all, so this has to be loud rather than quietly returning garbage.
    raise FileNotFoundError(
        "BIP-39 wordlist not found. Looked in "
        # Trimmed, because the upward walk generates one candidate per ancestor
        # and a message listing eight paths up to the drive root buries the two
        # that anybody can act on.
        + ", ".join(str(c) for c in candidates[:3])
        + f" (and {max(0, len(candidates) - 3)} further ancestors)")


# ── Wordlist ─────────────────────────────────────────────────────────────────

def load_wordlist() -> list[str]:
    """Load the bundled 2048-word BIP-39 English wordlist."""
    try:
        words = _wordlist_path().read_text(encoding="utf-8").split()
        if len(words) != 2048:
            raise ValueError(f"wordlist has {len(words)} entries, expected 2048")
        return words
    except Exception as e:
        log.error(f"Failed to load wordlist: {e}")
        raise


# ── BIP-39 mnemonic math (inlined from V1's backup_manager.py) ──────────────

def _wordlist_shape_error(wordlist: list[str]) -> Optional[str]:
    """Structural checks a wordlist must pass before it's safe to use for
    either generation or validation — shared by both so a malformed list
    can never get one function to accept a phrase the other then rejects,
    which would silently lock the user out of a key they just generated."""
    if len(wordlist) != 2048:
        return "Wordlist must contain exactly 2048 words"
    seen = set()
    for w in wordlist:
        if not w or w != w.strip() or " " in w:
            return f"Wordlist contains a blank or malformed entry: {w!r}"
        if w in seen:
            return f"Wordlist has duplicate entry: '{w}'"
        seen.add(w)
    return None


def validate_mnemonic(mnemonic: str, wordlist: list[str] | None = None) -> tuple[bool, str]:
    """BIP-39-style checksum validation of a 12-word mnemonic against the
    bundled 2048-word wordlist."""
    if wordlist is None:
        wordlist = load_wordlist()
    words = mnemonic.strip().lower().split()
    if len(words) != 12:
        return False, f"Expected 12 words, got {len(words)}"

    shape_error = _wordlist_shape_error(wordlist)
    if shape_error:
        return False, shape_error

    unknown = [w for w in words if w not in wordlist]
    if unknown:
        return False, f"Unknown words: {', '.join(unknown)}"

    try:
        # BIP-39: 12 words × 11 bits = 132 bits = 128-bit entropy + 4-bit checksum
        word_to_idx = {w: i for i, w in enumerate(wordlist)}
        indices = [word_to_idx[w] for w in words]
        bits = "".join(f"{i:011b}" for i in indices)
        entropy_bits = bits[:128]
        checksum_bits = bits[128:]          # 4 bits

        entropy_bytes = int(entropy_bits, 2).to_bytes(16, "big")
        digest = hashlib.sha256(entropy_bytes).digest()
        expected_checksum = f"{digest[0]:08b}"[:4]

        if checksum_bits != expected_checksum:
            return False, "Checksum invalid — check for typos"
    except Exception as e:
        return False, f"Validation error: {e}"

    return True, ""


def generate_mnemonic(wordlist: list[str] | None = None) -> str:
    """Generate a cryptographically secure 12-word BIP-39 mnemonic.
    128 random bits + 4-bit SHA-256 checksum = 12 × 11-bit word indices."""
    if wordlist is None:
        wordlist = load_wordlist()
    shape_error = _wordlist_shape_error(wordlist)
    if shape_error:
        raise ValueError(shape_error)

    entropy = secrets.token_bytes(16)                       # 128 bits
    digest = hashlib.sha256(entropy).digest()

    entropy_bits = "".join(f"{b:08b}" for b in entropy)    # 128 bits
    checksum_bits = f"{digest[0]:08b}"[:4]                  # 4 bits
    all_bits = entropy_bits + checksum_bits                  # 132 bits

    indices = [int(all_bits[i*11:(i+1)*11], 2) for i in range(12)]
    return " ".join(wordlist[i] for i in indices)


# ── Key derivation ───────────────────────────────────────────────────────────

def derive_key(mnemonic: str) -> bytes:
    """
    PBKDF2-SHA512(mnemonic, 'primnox2-local', 600_000 iterations) → 32-byte
    AES-256 key. Deterministic: same mnemonic always gives the same key.

    Whitespace is normalized to match validate_mnemonic()'s tolerance for
    stray double-spaces/tabs, so a typo in spacing doesn't silently derive a
    different key and lock the user out.
    """
    normalized = " ".join(mnemonic.strip().lower().split())
    return hashlib.pbkdf2_hmac(
        "sha512",
        normalized.encode("utf-8"),
        _SALT,
        600_000,
        dklen=32,
    )


# ── OS keychain helpers ─────────────────────────────────────────────────────

def _keychain_store(key: bytes) -> None:
    try:
        import keyring
        keyring.set_password(_KEYRING_SERVICE, _KEYRING_USER, key.hex())
    except Exception as e:
        log.warning(f"Could not store vault key in keychain: {e}")


def _keychain_load() -> Optional[bytes]:
    try:
        import keyring
        val = keyring.get_password(_KEYRING_SERVICE, _KEYRING_USER)
        return bytes.fromhex(val) if val else None
    except Exception:
        return None


def _keychain_clear() -> None:
    try:
        import keyring
        keyring.delete_password(_KEYRING_SERVICE, _KEYRING_USER)
    except Exception:
        pass


def _keychain_store_phrase(mnemonic: str) -> None:
    try:
        import keyring
        keyring.set_password(_KEYRING_SERVICE, _KEYRING_USER_PHRASE, mnemonic)
    except Exception as e:
        log.warning(f"Could not store vault phrase in keychain: {e}")


def _keychain_load_phrase() -> Optional[str]:
    try:
        import keyring
        return keyring.get_password(_KEYRING_SERVICE, _KEYRING_USER_PHRASE)
    except Exception:
        return None


def _keychain_clear_phrase() -> None:
    try:
        import keyring
        keyring.delete_password(_KEYRING_SERVICE, _KEYRING_USER_PHRASE)
    except Exception:
        pass


# ── File encryption helpers ─────────────────────────────────────────────────

def _encrypt_bytes(data: bytes, key: bytes) -> bytes:
    nonce = secrets.token_bytes(12)
    compressed = gzip.compress(data)
    ct = AESGCM(key).encrypt(nonce, compressed, None)
    return MAGIC + bytes([VERSION]) + nonce + ct


def _decrypt_bytes(blob: bytes, key: bytes) -> bytes:
    if blob[:4] != MAGIC:
        raise ValueError("Not a Primnox2 vault file (bad magic)")
    if blob[4] != VERSION:
        raise ValueError(f"Unsupported vault version: {blob[4]}")
    nonce = blob[5:17]
    ct = blob[17:]
    compressed = AESGCM(key).decrypt(nonce, ct, None)
    return gzip.decompress(compressed)


def _secure_delete(path: Path) -> None:
    """Best-effort overwrite-then-delete of a plaintext file (full file, not
    capped at any fixed size)."""
    try:
        size = path.stat().st_size
        chunk = 64 * 1024  # 64 KB chunks to avoid one giant allocation
        with open(path, "wb") as f:
            remaining = size
            while remaining > 0:
                f.write(secrets.token_bytes(min(chunk, remaining)))
                remaining -= chunk
            f.flush()
            os.fsync(f.fileno())
    except Exception:
        pass
    try:
        path.unlink()
    except FileNotFoundError:
        pass


# ── Vault lifecycle ──────────────────────────────────────────────────────────

def vault_path(db_path: Path) -> Path:
    return db_path.with_suffix(db_path.suffix + ".vault")


def is_enabled(db_path: Path) -> bool:
    """A vault is 'enabled' for this DB if a .vault file exists for it."""
    return vault_path(db_path).exists()


def is_locked(db_path: Path) -> bool:
    """Locked = vault file exists but no plaintext DB is present."""
    return is_enabled(db_path) and not db_path.exists()


def setup_vault(db_path: Path, mnemonic: Optional[str] = None) -> str:
    """
    Enable the vault for db_path.

    - If mnemonic is None, a fresh one is generated and returned (the
      caller MUST show this to the user — it cannot be recovered later).
    - If mnemonic is provided, it must be a valid 12-word phrase.

    Encrypts the current plaintext db (if any) into db_path.vault, caches the
    derived key in the OS keychain, and leaves the plaintext db in place — see
    the module docstring's safety model. Safe to call at any time.
    """
    if mnemonic is None:
        mnemonic = generate_mnemonic()
    else:
        ok, err = validate_mnemonic(mnemonic)
        if not ok:
            raise ValueError(f"Invalid mnemonic: {err}")

    key = derive_key(mnemonic)

    if db_path.exists():
        data = db_path.read_bytes()
        blob = _encrypt_bytes(data, key)
        vault_path(db_path).write_bytes(blob)
    else:
        # Nothing to encrypt yet — create an empty encrypted placeholder
        vault_path(db_path).write_bytes(_encrypt_bytes(b"", key))

    _keychain_store(key)
    _keychain_store_phrase(mnemonic)
    log.info(f"Local vault enabled for {db_path.name}")
    return mnemonic


def unlock_vault(db_path: Path, mnemonic: Optional[str] = None) -> None:
    """
    Decrypt db_path.vault → db_path (plaintext) using either the supplied
    mnemonic or the key cached in the OS keychain.

    Only call this before storage.db.configure()/db.init() run — see the
    module docstring's safety model.
    """
    vp = vault_path(db_path)
    if not vp.exists():
        raise FileNotFoundError(f"No vault found at {vp}")

    if mnemonic:
        ok, err = validate_mnemonic(mnemonic)
        if not ok:
            raise ValueError(f"Invalid mnemonic: {err}")
        key = derive_key(mnemonic)
    else:
        key = _keychain_load()
        if key is None:
            raise PermissionError("Vault is locked and no key in keychain — mnemonic required")

    blob = vp.read_bytes()
    try:
        data = _decrypt_bytes(blob, key)
    except Exception:
        raise PermissionError("Incorrect mnemonic — could not decrypt vault")

    if data:
        db_path.write_bytes(data)
    if mnemonic:
        _keychain_store(key)
    log.info(f"Local vault unlocked for {db_path.name}")


def lock_vault(db_path: Path, key: Optional[bytes] = None) -> None:
    """
    Re-encrypt the current plaintext db_path → db_path.vault and securely
    delete the plaintext copy. Call only on clean shutdown, after the
    scheduler's workers have stopped — see the module docstring.

    _secure_delete() overwrites the plaintext file in place before unlinking
    it — if the process is killed mid-overwrite, the plaintext DB is left
    corrupted with a malformed disk image, and there is otherwise no check
    that a *good* .vault copy actually exists before that happens. Decrypting
    the just-written .vault blob back and confirming it matches before
    touching the plaintext turns "corrupt the only copy" into "worst case,
    skip the delete and leave plaintext as-is."
    """
    if not db_path.exists():
        return
    if key is None:
        key = _keychain_load()
    if key is None:
        log.warning("lock_vault: no key available, skipping re-encrypt (plaintext left as-is)")
        return

    data = db_path.read_bytes()
    blob = _encrypt_bytes(data, key)
    vp = vault_path(db_path)
    vp.write_bytes(blob)

    try:
        roundtrip = _decrypt_bytes(vp.read_bytes(), key)
    except Exception as e:
        log.error(f"lock_vault: .vault blob failed to verify after write ({e}) — leaving plaintext in place")
        return
    if roundtrip != data:
        log.error("lock_vault: .vault blob does not match source data after write — leaving plaintext in place")
        return

    _secure_delete(db_path)
    log.info(f"Local vault locked for {db_path.name}")


def sync_vault(db_path: Path) -> None:
    """
    Re-encrypt db_path → db_path.vault WITHOUT deleting the plaintext.
    Periodic snapshot while the app keeps running. Safe to call at any time,
    for the same reason setup_vault() is.
    """
    if not db_path.exists() or not is_enabled(db_path):
        return
    key = _keychain_load()
    if key is None:
        return
    data = db_path.read_bytes()
    vault_path(db_path).write_bytes(_encrypt_bytes(data, key))


def disable_vault(db_path: Path) -> None:
    """Decrypt (if locked) and remove the .vault file + keychain entry."""
    if is_locked(db_path):
        unlock_vault(db_path)
    vp = vault_path(db_path)
    if vp.exists():
        vp.unlink()
    _keychain_clear()
    _keychain_clear_phrase()
    log.info(f"Local vault disabled for {db_path.name}")


def get_stored_phrase() -> Optional[str]:
    """Retrieve the mnemonic stored in the OS keychain (set during
    setup_vault). Returns None if the vault was set up without mnemonic
    storage or has been disabled."""
    return _keychain_load_phrase()
